logging:
  file:
    name:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: DEBUG
    org.hibernate.stat: DEBUG
spring:
  jpa:
    show-sql: true



